#  产品主表
CREATE TABLE IF NOT EXISTS `product`(
    `product_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '产品ID',
    `product_sku` varchar(60) DEFAULT NULL,
    `customer_id` int(11) NOT NULL DEFAULT '1' COMMENT '用户ID',
    `product_title_en` varchar(255) DEFAULT '' COMMENT '产品名称',
    `product_title` varchar(255) DEFAULT '' COMMENT '中文描述',
    `product_status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '产品状态:0 删除,1正式产品',
    `sale_status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0未指定，1新品，2正常销售，3重点产品，4缺货中，5清仓，6停售',
    `hs_code` varchar(32) NOT NULL DEFAULT '' COMMENT '商品海关编码',
    `currency_code` varchar(5) NOT NULL DEFAULT '' COMMENT '申报币种',
    `pu_code` varchar(5) DEFAULT '' COMMENT '产品单位EA(单个) KG(公斤) MT(米) CASE(盒) PC(件) SET(套)',
    `product_length` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '产品长',
    `product_width` decimal(5,2) DEFAULT '0.00' COMMENT '宽度',
    `product_height` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '高',
    `product_net_weight` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '产品净重(KG)',
    `product_weight` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '产品重量(KG)',
    `product_sales_value` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '销售价',
    `product_purchase_value` decimal(11,4) unsigned NOT NULL DEFAULT '0.0000' COMMENT '采购价',
    `product_declared_value` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '申报价值',
    `product_is_combination` tinyint(1) DEFAULT '0' COMMENT '是否是组合产品（0：否1：是）',
    `product_barcode_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '条形码类型：0:默认条码;1:自定义条码;2:序列号;',
    `pc_id` int(11) NOT NULL DEFAULT '0' COMMENT '产品分类',
    `pc_attr` int(11) NOT NULL DEFAULT '0' COMMENT '产品属性',
    `product_add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '产品添加时间',
    `product_update_time` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '产品最后更新时间',
    `contain_battery` tinyint(1) NOT NULL DEFAULT '0' COMMENT '含电池:  0,不含 1:含',
    `prl_id` tinyint(1) DEFAULT '0' COMMENT '产品等级',
    `parent_product_id` int(11) DEFAULT '0' COMMENT '关联的母SKU ID',
    `seller_id` int(10) NOT NULL DEFAULT '0' COMMENT '销售员',
    `fbo_tax_rate` float(6,3) DEFAULT '0.000' COMMENT 'FOB税率',
    `exp_date` int(11) NOT NULL DEFAULT '0' COMMENT '有效期天数',
    `warehouse_barcode` varchar(32) NOT NULL DEFAULT '' COMMENT '仓库条码',
    `gross_rofit` float(6,3) NOT NULL DEFAULT '0.000' COMMENT '毛利率',
    `tax_rate` float(6,3) NOT NULL DEFAULT '0.000' COMMENT '税率',
    `default_warehouse_id` int(11) DEFAULT NULL COMMENT '默认发货仓库',
    `product_declaration_statement` varchar(64) NOT NULL DEFAULT '' COMMENT '申报说明，关于申报信息上的扩展，如在此块填写HTS CODE',
    `product_specs` varchar(255) NOT NULL DEFAULT '' COMMENT '规格',
    `prt_id` tinyint(1) NOT NULL DEFAULT '0' COMMENT '侵权等级',
    PRIMARY KEY (`product_id`),
    KEY `product_product_sku_id` (`product_sku`),
    KEY `product_update_time` (`product_update_time`),
    KEY `product_sku` (`product_sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='产品主表';

#.产品分类
CREATE TABLE IF NOT EXISTS `product_category`(
    `pc_id` int(11) NOT NULL AUTO_INCREMENT,
    `warehouse_id` int(11) NOT NULL DEFAULT '0' COMMENT '仓库ID/0为共用',
    `pc_name_en` varchar(255) NOT NULL DEFAULT '' COMMENT '英文',
    `pc_name` varchar(255) NOT NULL DEFAULT '' COMMENT '中文描述',
    `pc_shortname` varchar(8) NOT NULL DEFAULT '' COMMENT '简写',
    `pc_hs_code` varchar(255) NOT NULL DEFAULT '' COMMENT '海关品名',
    `pc_sort_id` tinyint(3) NOT NULL DEFAULT '0' COMMENT '排序ID(0~999)',
    `pc_update_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '添加/更新时间',
    `pc_pid` int(11) DEFAULT '0' COMMENT '父级ID',
    `pc_level` tinyint(1) DEFAULT '0' COMMENT '层级 ',
    `pc_like` varchar(255) DEFAULT NULL,
    `pc_reference_code` varchar(32) NOT NULL DEFAULT '' COMMENT '参考码',
    PRIMARY KEY (`pc_id`),
    KEY `pc_pid` (`pc_pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='产品分类';

#.产品属性
CREATE TABLE IF NOT EXISTS `product_attr`(
    `pa_id` INT (11) NOT NULL AUTO_INCREMENT,
    `pa_descript` varchar(255) NOT NULL DEFAULT '' COMMENT '中文描述',
    `pa_descript_en` varchar(255) NOT NULL DEFAULT '' COMMENT '英文描述',
    `pa_attr_key` varchar(255) NOT NULL DEFAULT '' COMMENT '属性名（key）',
    `pa_attr_val` varchar(255) NOT NULL DEFAULT '' COMMENT '属性值（val）',
    `pa_parent_id` int(11) DEFAULT '0' COMMENT '父级ID',
    `pa_level` tinyint(1) DEFAULT '0' COMMENT '层级 ',
    `pc_update_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '添加/更新时间',
    PRIMARY KEY (`pa_id`),
    KEY `pa_parent_id` (`pa_parent_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='产品属性';


#用户授权表
CREATE TABLE IF NOT EXISTS `user_system_authorization`(
    `usa_id` int(11) NOT NULL AUTO_INCREMENT,
    `user_id` int(11) NOT NULL DEFAULT '0' COMMENT '用户ID',
    `usa_online_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '在线状态:0,离线中 1,在线中',
    `usa_auth_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '授权状态:0,未授权 1,已授权',
    `usa_auth_code` text NOT NULL COMMENT '授权码',
    `usa_quick_login` tinyint(1) NOT NULL DEFAULT '0' COMMENT '快捷登录 1：免密码',
    `usa_add_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
    `usa_update_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
    `usa_auth_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '授权时间',
    `usa_login_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '登录时间',
    `usa_logout_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '登出时间',
    PRIMARY KEY (`usa_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户系统授权列表';

#订单表
CREATE TABLE IF NOT EXISTS `orders`(
    `order_id` int(11) NOT NULL AUTO_INCREMENT,
    `order_code` varchar(32) NOT NULL DEFAULT '' COMMENT '订单序列',
    `platform` varchar(20) NOT NULL DEFAULT '' COMMENT '平台代码',
    `order_platform_type` varchar(20) NOT NULL DEFAULT '' COMMENT '平台类型',
    `order_platform_code` varchar(64) NOT NULL DEFAULT '' COMMENT '平台真实订单号',
    `create_type` varchar(20) NOT NULL DEFAULT '' COMMENT '创建类型:api,upload,hand',
    `warehouse_id` int(11) NOT NULL DEFAULT '0' COMMENT '仓库id',
    `to_warehouse_id` int(11) NOT NULL DEFAULT '0' COMMENT '目的仓库',
    `order_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '类型：0:普通 ;1:退货;2:重发',
    `country_code` char(4) NOT NULL DEFAULT '' COMMENT '国家二字码',
    `parcel_declared_value` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '物品申报价值,下单时填写,非SKU加总',
    `declared_weight` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '申报重量',
    `shipping_fee_estimate` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '运费估算',
    `currency_code` varchar(5) NOT NULL DEFAULT '' COMMENT '币种Code',
    `parcel_contents` varchar(255) NOT NULL DEFAULT '' COMMENT '物品内容描述（内装何物）下单时填写',
    `parcel_quantity` int(11) NOT NULL DEFAULT '0' COMMENT '内件数量',
    `order_status` tinyint(3) NOT NULL DEFAULT '1' COMMENT '订单状态--- 0:删除;1:草稿;2:确认;3:异常;4:已提交;5:已打印;6:已下架;7:已打包;8:已装袋;9:装袋完成;10:已加挂;11:物流完成;12:物流发货;13:已签收',
    `order_hold_inventory` tinyint(1) NOT NULL DEFAULT '0' COMMENT '占用库存 1:是 0:否',
    `order_exception_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '异常状态 0:无 1:',
    `order_waiting_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '等待状态0:无;1:物流处理',
    `print_quantity` int(5) NOT NULL DEFAULT '0' COMMENT '标签打印次数',
    `add_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '订单加入时间',
    `update_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后修改时间',
    `order_paydate` datetime DEFAULT '0000-00-00 00:00:00' COMMENT '付款时间',
    `reference_no` varchar(50) NOT NULL DEFAULT '' COMMENT '客户参考号',
    `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
    `site_id` varchar(64) NOT NULL DEFAULT '' COMMENT '站点',
    `seller_id` varchar(128) NOT NULL DEFAULT '' COMMENT '卖家ID',
    `sync_count` int(11) NOT NULL DEFAULT '0' COMMENT '记录同步次数',
    `sync_express_ship` tinyint(1) NOT NULL DEFAULT '0' COMMENT '物流跟踪标记 0 未发货 1 已发货 2 已签收',
    PRIMARY KEY (`order_id`),
    KEY `reference_no` (`reference_no`) USING BTREE,

) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单信息表';

#订单标签表
CREATE TABLE IF NOT EXISTS `order_label_url`(
    `olu_id` int(11) NOT NULL AUTO_INCREMENT,
    `order_code` varchar(32) NOT NULL DEFAULT '' COMMENT '订单号',
    `olu_url` varchar(250) NOT NULL DEFAULT '' COMMENT '网址',
    `olu_file_type` varchar(20) NOT NULL DEFAULT '' COMMENT '文件类型：png',
    `olu_label_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '标签类型：0=label,1=invoice,2=return label',
    `olu_create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `ol_update_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后修改时间',
    PRIMARY KEY (`olu_id`),
    KEY `order_code` (`order_code`),
    KEY `olu_file_type` (`olu_file_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='标签图片地址表';

#订单属性表
CREATE TABLE IF NOT EXISTS `order_additional` (
  `oa_id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) NOT NULL DEFAULT '0' COMMENT '订单ID',
  `order_code` varchar(50) NOT NULL DEFAULT '' COMMENT '订单号',
  `picking_mode` tinyint(2) NOT NULL DEFAULT '0' COMMENT '拣货模式 1：按单  2：集中',
  `estimate_weight` decimal(11,3) NOT NULL DEFAULT '0.000' COMMENT '预估重量',
  `address_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0,未处理 1,UnClassified 2,Commercial 3,Residential 4,unknown',
  `ignore_address_verify` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1:忽略地址验证',
  `ship_order_value` text NOT NULL COMMENT '预报订单后需要保存的某些数据',
  `declare_value` float(20,2) NOT NULL DEFAULT '0.00' COMMENT '订单申报价值',
  `declare_currency` varchar(32) NOT NULL DEFAULT 'USD' COMMENT '订单申报价值币种',
  `cob_no` varchar(50) NOT NULL DEFAULT '' COMMENT '总单号',
  `oa_volume_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否自定义体积，0-否 1-是',
  `oa_length` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '长',
  `oa_width` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '宽',
  `oa_height` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '高',
  `eb_source` varchar(100) DEFAULT NULL,
  `oa_is_insurance` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否投保',
  `oa_insurance_value` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '投保金额',
  `oa_is_checking` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否对账',
  `oa_import_count` int(11) NOT NULL DEFAULT '0' COMMENT '订单导入次数（用于非API发货）',
  `oa_is_check_egd` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'EGD订单预报是否校验订单为担保订单  0：不校验 ，1：校验',
  `oa_is_combination` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否组合订单 0-否 1-是',
  `oa_wish_combined_order` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'EPC订单支持相同订单合并预报',
  `oa_account_tax_id` varchar(64) DEFAULT '' COMMENT '申报税号',
  `oa_invoice_rule_limit` tinyint(1) NOT NULL DEFAULT '0' COMMENT '组合订单的申报价值是否按运输方式管理的发票规则进行限制 0-否 1-是',
  `oa_is_print` tinyint(1) NOT NULL DEFAULT '0' COMMENT '标签是否已打印 0-否 1-是（暂时只适用于单据打印）',
  `oa_dps_id` int(11) NOT NULL DEFAULT '0' COMMENT '申报包裹设置ID',
  `oa_financial_remark` varchar(2000) NOT NULL DEFAULT '' COMMENT '财务备注',
  `oa_order_info` varchar(2000) NOT NULL DEFAULT '' COMMENT '订单明细数据',
  `oa_weight` decimal(10,3) NOT NULL DEFAULT '0.000' COMMENT '重量',
  `oa_country_code` char(4) NOT NULL DEFAULT '' COMMENT '转国家二字码',
  `oa_city` varchar(60) NOT NULL DEFAULT '' COMMENT '转城市代号',
  `lock_inventory_model` tinyint(2) NOT NULL DEFAULT '1' COMMENT '订单锁库存模式 1:锁库存模式，2：锁库存批次模式',
  PRIMARY KEY (`oa_id`),
  KEY `order_code` (`order_code`),
  KEY `oa_order_id` (`order_id`,`oa_is_checking`) USING BTREE,
  KEY `idx_is_checking` (`oa_is_checking`)
) ENGINE=InnoDB AUTO_INCREMENT=69846 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='订单属性表(一对一)';