INSERT INTO `product`(`product_id`, `product_sku`, `customer_id`, `product_title_en`, `product_title`, `product_status`, `sale_status`, `hs_code`, `currency_code`, `pu_code`, `product_length`, `product_width`, `product_height`, `product_net_weight`, `product_weight`, `product_sales_value`, `product_purchase_value`, `product_declared_value`, `product_is_combination`, `product_barcode_type`, `pc_id`, `pc_attr`, `product_add_time`, `product_update_time`, `contain_battery`, `prl_id`, `parent_product_id`, `seller_id`, `fbo_tax_rate`, `exp_date`, `warehouse_barcode`, `gross_rofit`, `tax_rate`, `default_warehouse_id`, `product_declaration_statement`, `product_specs`, `prt_id`) VALUES (1, '001-M-RD-T-002', 1, 'turn_light-middle-RED-T型-宝马A', '转向灯-中码[M]-红色[RD]-T型[T]-宝马-CBR1000-2008[002]', 1, 1, '0', 'USD', '001', 10.00, 10.00, 10.00, 0.500, 0.000, 0.00, 1.0000, 2.00, 0, 0, 0, 0, '2019-07-30 14:28:38', '0000-00-00 00:00:00', 0, 0, 0, 0, 0.000, 0, '', 0.000, 0.000, NULL, '', '', 0);
INSERT INTO `product`(`product_id`, `product_sku`, `customer_id`, `product_title_en`, `product_title`, `product_status`, `sale_status`, `hs_code`, `currency_code`, `pu_code`, `product_length`, `product_width`, `product_height`, `product_net_weight`, `product_weight`, `product_sales_value`, `product_purchase_value`, `product_declared_value`, `product_is_combination`, `product_barcode_type`, `pc_id`, `pc_attr`, `product_add_time`, `product_update_time`, `contain_battery`, `prl_id`, `parent_product_id`, `seller_id`, `fbo_tax_rate`, `exp_date`, `warehouse_barcode`, `gross_rofit`, `tax_rate`, `default_warehouse_id`, `product_declaration_statement`, `product_specs`, `prt_id`) VALUES (2, 'TX50031', 1, 'Apple iPhoneXS 256GB gold 4G phone', 'Apple iPhoneXS 256GB 金色 4G手机', 1, 1, '0', 'USD', '001', 90.00, 90.00, 90.00, 0.500, 0.000, 0.00, 1.0000, 2.00, 0, 0, 0, 0, '2019-07-30 14:28:38', '0000-00-00 00:00:00', 0, 0, 0, 0, 0.000, 0, '', 0.000, 0.000, NULL, '', '', 0);
INSERT INTO `product`(`product_id`, `product_sku`, `customer_id`, `product_title_en`, `product_title`, `product_status`, `sale_status`, `hs_code`, `currency_code`, `pu_code`, `product_length`, `product_width`, `product_height`, `product_net_weight`, `product_weight`, `product_sales_value`, `product_purchase_value`, `product_declared_value`, `product_is_combination`, `product_barcode_type`, `pc_id`, `pc_attr`, `product_add_time`, `product_update_time`, `contain_battery`, `prl_id`, `parent_product_id`, `seller_id`, `fbo_tax_rate`, `exp_date`, `warehouse_barcode`, `gross_rofit`, `tax_rate`, `default_warehouse_id`, `product_declaration_statement`, `product_specs`, `prt_id`) VALUES (3, 'TX50030', 1, 'Chinese style T-shirt', '中国风立体印花花T恤', 1, 1, '0', 'USD', '001', 70.00, 70.00, 70.00, 0.500, 0.000, 0.00, 1.0000, 2.00, 0, 0, 0, 0, '2019-07-30 14:28:38', '0000-00-00 00:00:00', 0, 0, 0, 0, 0.000, 0, '', 0.000, 0.000, NULL, '', '', 0);
INSERT INTO `product`(`product_id`, `product_sku`, `customer_id`, `product_title_en`, `product_title`, `product_status`, `sale_status`, `hs_code`, `currency_code`, `pu_code`, `product_length`, `product_width`, `product_height`, `product_net_weight`, `product_weight`, `product_sales_value`, `product_purchase_value`, `product_declared_value`, `product_is_combination`, `product_barcode_type`, `pc_id`, `pc_attr`, `product_add_time`, `product_update_time`, `contain_battery`, `prl_id`, `parent_product_id`, `seller_id`, `fbo_tax_rate`, `exp_date`, `warehouse_barcode`, `gross_rofit`, `tax_rate`, `default_warehouse_id`, `product_declaration_statement`, `product_specs`, `prt_id`) VALUES (4, 'HONGYUA002TESWTE', 1, 'STEWTREW', 'STEWTREW', 1, 1, '0', 'USD', '001', 2.00, 2.00, 2.00, 1.500, 0.000, 0.00, 1.0000, 2.00, 0, 0, 0, 0, '2019-07-30 14:28:38', '0000-00-00 00:00:00', 0, 0, 0, 0, 0.000, 0, '', 0.000, 0.000, NULL, '', '', 0);




INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (1, 0, 'Cloth', '服装', '1', '', 0, '2019-06-15 10:50:37', 0, 0, '1-','1');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (2, 0, 'SY', '上衣', '2', 'SY01', 0, '2018-06-05 20:22:30', 1, 1, '1-2-', 'S');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (3, 0, 'TX', 'T恤', '3', 'TX01', 0, '2018-11-28 16:01:26', 2, 2, '1-2-3-', 'TOMAS01');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (4, 0, 'LY', '连衣裙', '4', '', 0, '2018-11-28 16:38:55', 2, 2, '1-2-4-', 'TOMAS01');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (5, 0, '3c', '数码3C', '5', '333', 0, '2019-04-23 10:14:21', 0, 0, '5-', '1233ANDDDDD');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (7, 0, 'Sports', '运动', '7', '11', 0, '2018-06-09 17:44:48', 0, 0, '7-', '2323DEF');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (8, 0, 'BasketBall', '篮球', '8', '111', 0, '2018-06-09 17:17:58', 7, 1, '7-8-', 'SE');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (9, 0, 'T Shirt', 'T 恤', '9', '111', 0, '2017-08-11 09:32:32', 7, 1, '7-9-', '');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (10, 0, 'Fruit', '水果', '10', '111', 0, '2017-08-11 09:43:16', 0, 0, '10-','');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (11, 0, 'HuoLongGuo', '火龙果', '11', '111', 0, '2017-08-11 10:05:16', 10, 1, '10-11-', '');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (12, 0, 'Toy', '玩具', '12', '111', 0, '2019-04-30 14:19:26', 0, 0, '12-', '');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (13, 0, 'JIAJU', '家具类', '13', '111', 0, '2017-08-11 11:30:32', 0, 0, '13-', '');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (16, 0, 'PiDai', '皮带', '16', '11', 0, '2017-08-17 10:17:09', 13, 1, '13-16-', '');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (17, 0, 'MaoRong', '毛绒玩具1', '17', '111', 0, '2019-05-10 10:22:54', 12, 1, '12-17-', '');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (18, 0, 'Computer', '电脑', '18', '', 0, '2017-08-17 11:29:12', 5, 1, '5-18-', '');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (19, 0, '床具sdf', '床具', '19', '', 0, '2018-06-09 17:16:37', 0, 0, '19-', 'SDF');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (20, 0, '武器', '武器', '20', '', 0, '2017-08-31 14:14:27', 0, 0, '20-', '');
INSERT INTO `product_category`(`pc_id`, `warehouse_id`, `pc_name_en`, `pc_name`, `pc_shortname`, `pc_hs_code`, `pc_sort_id`, `pc_update_time`, `pc_pid`, `pc_level`, `pc_like`,  `pc_reference_code`) VALUES (21, 0, '战斗机', '战斗机', '21', '', 0, '2017-08-22 16:57:39', 20, 1, '20-21-', '');